spring:
  application:
    name: Gateway-
  server:
    port: 8083
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
    gateway:
      routes:
        - id: my_route
          uri: http://localhost:8082/
          predicates:
            - Path=/customer/


